### ISSUE TITLE
Trouble setting up project with init

### ISSUE THREAD

**Issue by renaatdemuynck** [harvard-edtech/caccl#13]
Hi, I'm having trouble setting up a project using `npm init caccl`. 

    root@ubuntu-bionic:/vagrant# npm init caccl
    internal/modules/cjs/loader.js:883
      throw err;
      ^

    Error: Cannot find module '/root/.npm/_npx/11188/lib/node_modules/create-caccl/node_modules/ejs/postinstall.js'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
        at Function.Module._load (internal/modules/cjs/loader.js:725:27)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
        at internal/main/run_main_module.js:17:47 {
      code: 'MODULE_NOT_FOUND',
      requireStack: []
    }
    npm ERR! Maximum call stack size exceeded

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2021-04-13T20_58_49_384Z-debug.log
    Install for [ 'create-caccl@latest' ] failed with code 1

Any help would be really appreciated. Thank you!

I'm using Vagrant to run Ubuntu 18.04 LTS (Bionic Beaver) on a Windows 10 host. 
**Node vesion**: 14.16.1
**NPM version**: 6.14.12

**Comment by renaatdemuynck** [comment]
Tried a couple of times with different Ubuntu boxes, but same result.
Ended up using WSL with Ubuntu 18.04. Just needed to install NVM to get the latest Node version. Works like a charm!
