### ISSUE TITLE
Unable to deploy on server

### ISSUE THREAD

**Issue by adamtyoung** [harvard-edtech/caccl#2]
Even if I create a vanilla CACCL app, when I run `npm run build` and then `npm start` I get this:

events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:443
    at Server.setupListenHandle [as _listen2] (net.js:1241:19)
    at listenInCluster (net.js:1306:12)
    at Server.listen (net.js:1394:7)
    at module.exports (/home/aya16/lti-final/node_modules/caccl/genExpressApp.js:157:12)
    at module.exports (/home/aya16/lti-final/node_modules/caccl/validateConfigAndSetDefaults/server.js:449:18)
    at module.exports (/home/aya16/lti-final/node_modules/caccl/server/index.js:116:18)
    at module.exports (/home/aya16/lti-final/node_modules/caccl/server/react.js:161:15)
    at Object.<anonymous> (/home/aya16/lti-final/index.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1285:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:871:11)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lti-final@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lti-final@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aya16/.npm/_logs/2019-04-04T23_10_47_675Z-debug.log

**Comment by gabeabrams** [comment]
This is actually a permissions error. The user you're using to start node is not allowed to start servers on port `443`.

I added "prettier" error messages. Please update caccl (`npm update` or `npm i --save caccl) and try again for better error messages.

How to fix this issue:
Either start the app using an admin/root user or start the app using `sudo`. A safer but more complex solution would actually be to use something like nginx to listen to port 443 or 80 and forward traffic to your app, which you can set up to listen on port 8080 (for example). Search the docs for "Which port will my app listen to" to get more information on switching ports.

Does this help?

**Comment by adamtyoung** [comment]
Yes that is very clear. Thanks again.
